---

stages:
  - lint
  - test
  - min-coverage

variables:
  MIN_COVERAGE: 70

pylint:
  stage: lint
  image: python:3-slim
  before_script:
    - python3.10 -m pip install poetry
    - poetry install
  script:
    - poetry run pylint bookmarker tests

pytest:
  stage: test
  image: python:3-slim
  services:
    - name: postgres:14
  variables:
    POSTGRES_DB: fastapi_template
    POSTGRES_USER: user
    POSTGRES_PASSWORD: random
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  before_script:
    - python3.10 -m pip install poetry
    - poetry install
  script:
    - poetry run pytest --verbosity=2 --showlocals --log-level=DEBUG --cov=src --cov-report html --cov-fail-under=$MIN_COVERAGE
